clear all
mex -g playrec.cpp audiodevice.cpp ../asio/common/asio.cpp ../asio/host/asiodrivers.cpp ../asio/host/pc/asiolist.cpp ...
    -I../asio/common ...
    -I../asio/host ...
    -I../asio/host/pc 

